# Generated by Django 5.2.4 on 2026-05-14 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\+7\\d{10}$', message='Номер должен быть в формате +7XXXXXXXXXX')], verbose_name='Телефон'),
        ),
    ]
